dataset_info:
  batch_size: 4
  dataset_name: thuman-cross-subject
  dataset_rng_seed: 1
  dataset_root_dir: ./dataset/THuman-mix-v1
  fov: 60.0
  height_px: 50
  k: 40
  load_pcd_with_mesh: true
  local_max_angle: 3.0
  max_angle: 180
  max_k_ratio: 1.2
  max_num_mesh: 2
  max_r: 3.0
  max_rnd_num_points: 2000000
  max_subsample: 1
  max_translate_ratio: 2.0
  min_k_ratio: 0.2
  min_num_mesh: 1
  min_r: 1.7
  min_rnd_num_points: 800000
  min_subsample: 1
  n_imgs: 30
  n_target_imgs: 4
  n_test_target_imgs: 4
  num_pcd: 2
  num_pcd_points: 100000
  num_threads: 4
  output_cam_mode: random
  pcd_subsample: 2
  perturb_camera_origin_rate: 0.05
  radius_scale: 2.0
  rand_r: 0.5
  random_rescale: true
  random_voxelization: 0.0
  ray_perturbation_angle: 3
  render_method: ray_cast
  rescale_pts: false
  sample_mode: uniform
  target_height_px: 512
  target_width_px: 512
  texture_crop_method: 20-200
  texture_filenames: null
  texture_mode: ori
  total: 400
  total_combined: null
  use_bucket_sampler: false
  voxelized: false
  width_px: 50
model_info:
  dim_feature: 8
  dim_input_layers:
  - 32
  - 64
  dim_mlp: 64
  direction_param: norm_vec
  dropout: 0.1
  estimate_image_rendering_weights: true
  estimate_surface_normal_weights: false
  learn_dist: false
  nonlinearity: silu
  num_heads: 4
  num_layers: 4
  positional_encoding_include_input: true
  positional_encoding_log_sampling: true
  positional_encoding_num_functions: 0
  pts_ckpt_path: ./pointersect/checkpoint/epoch700.pth
  use_dist_as_input: false
  use_dps_as_input: false
  use_dpsuv_as_input: true
  use_feature_indicator: true
  use_pr: true
  use_rgb_as_input: false
  use_rgb_indicator: false
  use_vdir_as_input: true
  use_zdir_as_input: true
optim_info:
  clip: 1.0
  color_gt_neighbor: 1
  focal_loss_alpha: 0.5
  focal_loss_gamma: 2.0
  learn_ray_rgb: false
  learning_rate: 1.0e-05
  load_optimizer: false
  loss_rgb_type: l1
  loss_weight_dc: 1.0
  loss_weight_hit: 0.01
  loss_weight_lpips: 0.0
  loss_weight_normal: 10.0
  loss_weight_normal_l1: 0.0
  loss_weight_normal_l2: 1.0
  loss_weight_normal_reg: 0.0
  loss_weight_point_normal: 0.0
  loss_weight_rgb: 0.01
  loss_weight_t: 0.01
  lr_factor: 0.1
  max_grad_val: 1.0
  num_warmup_steps: 4000
  optim_method: adam_tf
  pcd_noise_std: 0.0
  pts_loss_weight: 1
  train_mlp: 1
  train_pcgc: 1
  train_pts: 0
  use_amp: false
  use_color: 0
  use_pts: 0
  use_upsample_loss: 1
  weight_arap: -30
  weight_cd: 0.0
  weight_color: 1.0
  weight_lamda: 0.0005
pcml_info:
  clr_encoder_channels: 9 32 64 128 256 128
  coding_level: 1
  color_dim_feature: 32
  enable_opacity: true
  encoder_channels: 1 64 256 512 256 32
  entropy_model: hyperprior
  est_normal: true
  geo_dim_feature: 8
  geo_encoder_channels: 1 64 256 512 256 8
  hyper_entropy_model: gaussian
  hyper_level: 1
  hyper_qscale: 32
  load_color_ckpt: 0
  load_pcgc_ckpt: false
  load_pcml_ckpt: 1
  mlp_fitting_str: 256 128 64
  model_type: unet
  neighbor_k: 5
  normalize_camera_normal: true
  normalize_gt_normal: false
  normalize_normal: true
  normalize_point_normal: false
  pcgc_ckpt_path: ./add_models/pcgc/ckpts/r6_0.3bpp.pth
  pcml_ckpt_pth: ./add_models/1-17-3/train/checkpoint/epoch122.pth
  qscale: 32
  randomize_background: true
  sampling_strategy: v2
  scale_factor: 256
  sh_deg: 1
  sh_feat_deg: 0
  threshold_K: 27
  train_pcgc: false
  upsample_ratio: 8
  use_dc_offset: false
  use_offset: true
  use_opacity: false
  use_rotation: true
  use_scale: true
  white_back: false
process_info:
  ddp_type: ddp
  exclude_dirs:
  - artifacts
  - datasets
  - checkpoints
  - ./add_models/1-21-2/train/checkpoint
  - ./add_models/1-21-2/train/tensorboard
  - ./add_models/1-21-2/train/logs
  - ./add_models/1-21-2/train/plots
  - ./add_models/1-21-2/train/code
  - ./add_models/1-21-2/train/option
  - ./add_models/1-21-2/train/stats
  exp_tag: train
  exp_tag_first: true
  find_unused_parameters: false
  log_every_num_test_batch: 1
  log_every_num_train_batch: 1
  log_every_num_valid_batch: 1
  max_test_epoch_batches: 20
  max_train_epoch_batches: 600
  max_valid_epoch_batches: 5
  output_dir: ./add_models/1-21-2/
  save_every_num_epoch: 1
  save_pic_every_batch: 200
  statistics_flag: true
  test_every_num_epoch: 1
  use_torchrun: true
  validate_every_num_epoch: 1
  visualize_every_num_test_batch: 5
  visualize_every_num_train_batch: 200
  visualize_every_num_valid_batch: 10
